### ISSUE TITLE
Wait for jobs to complete

### ISSUE THREAD

**Issue by palmerabollo** [Opsfleet/depends-on#3]
Any chance you will implement waiting for jobs [as commented here](https://github.com/Opsfleet/depends-on/blob/master/src/depends-on.go#L58)? It would be really useful.

**Comment by meshok0** [comment]
We are using Helm and utilize its hooks functionality (
https://github.com/helm/helm/blob/master/docs/charts_hooks.md)  for jobs
that need to be run before pods.

But this functionality seems like to be easy to add. So, we'll  implement
it some time soon.
